version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    restart: always
    ports:
      - 3000:3000
    #networks:
    #  - my_network

  # Add more containers below (nginx, postgres, etc.)
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  my_network:
#    external: true
